### ISSUE TITLE
JS error with El Capitan 10.11.5

### ISSUE THREAD

**Issue by vrainip** [andresgottlieb/soundcast#60]
SoundCast is launching with following JS error, then menu icon is set but is not functional.
(OSX 10.11.5, Soundflower 2.0b2 — may be down, node.js 6.2.1)

Uncaught Exception:
SyntaxError: Unexpected token /
    at Object.parse (native)
    at /Users/nip/Documents nip/Téléchargements/soundcast.app/Contents/Resources/app/main.js:49:30
    at /Users/nip/Documents nip/Téléchargements/soundcast.app/Contents/Resources/app/node_modules/shelljs/src/exec.js:142:7
    at ChildProcess.exithandler (child_process.js:232:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

**Comment by luatnd** [comment]
Same as me with Standard installation method: https://github.com/andresgottlieb/soundcast#standard
But you'll get it work with this installation method: https://github.com/andresgottlieb/soundcast#caskroom-with-homebrew

**Comment by vrainip** [comment]
Thank you so much! it works now.

**Comment by sjgoalie** [comment]
I did the homebrew install and it's still not working, when I launch soundcast with the icon I get "Unexpected token e"  in main.js 49:30.  the brew install went fine, no errors.

**Comment by Jaapk** [comment]
Great initiative, did not get it working on 10.12 clean install. Issue similar to sjgoalie.

**Comment by jace** [comment]
Mine stopped working after upgrading to 10.11.6 this morning:
<img width="532" alt="screen shot 2016-10-10 at 9 01 16 am" src="https://cloud.githubusercontent.com/assets/26695/19226397/4e895e44-8ec8-11e6-85c7-48980e695aa4.png">

**Comment by zambonofkuka** [comment]
Same problem with 10.10.5 (Yosemite). Tried both installation methods. Not working:(

**Comment by mjball** [comment]
Same issue here – would post a screenshot but it would be identical to @jace's.
